Revamped API Documentation
algorithmiaio/api-docs pull request #36
Opened 2020-04-13 21:40 UTC by andryanmiller

Still proofing, but wanted to get this open for curious eyes to review. Instructions on how to initialize are present in the README.md. 

@bnlb, given that we're still using the same Slate commands, I believe there shouldn't be an impact to our dev-center build process, but would like to validate that with you nonetheless.

Open items remaining:
- [ ] Create dev-center documentation pertaining to admin API keys.
- [ ] Restore Algorithmia-specific styling.

2020-04-14 16:21 UTC, bnlb commented on README.md
> +A `build` directory will be created that contains all of the production-ready static assets for this documentation.
This worked great! Thanks for updating.

2020-04-14 16:40 UTC, bnlb commented on source/index.html.md
> +
`/getting-started` should be `/developers/getting-started`

2020-04-14 16:58 UTC, bnlb commented
The dev center builds were failing with this change. I was able to get it [working again](https://gitlab.com/algorithmia-eng/dev-center/-/jobs/510630410) with a few small changes to the Dockerfile [here](https://github.com/algorithmiaio/dev-center/compare/UXENG-2332?expand=1). Everything is working fine for me locally (both when running the api docs locally and also when piping through dev center locally), but we'll want to double check this in test before anything goes live.

2020-04-15 17:17 UTC, andryanmiller commented
> The dev center builds were failing with this change. I was able to get it [working again](https://gitlab.com/algorithmia-eng/dev-center/-/jobs/510630410) with a few small changes to the Dockerfile [here](https://github.com/algorithmiaio/dev-center/compare/UXENG-2332?expand=1). Everything is working fine for me locally (both when running the api docs locally and also when piping through dev center locally), but we'll want to double check this in test before anything goes live.

Good catch @bnlb! Will make sure we make those tweaks.

2020-04-17 20:18 UTC, andryanmiller commented
This branch is now being built in https://github.com/algorithmiaio/dev-center/pull/317, and additional content (such as the addition of docs for admin API keys) can also be found there.

2020-04-17 20:49 UTC, andryanmiller commented on source/includes/_algorithm_builds.md
> +An object containing the logs for an algorithm build, otherwise an [error](#errors). Note that, until a build's `status` attribute transitions to either `succeeded` or `failed`, logs will not be avai
💅 Typo: `requests logs`.

2020-04-20 22:21 UTC, andryanmiller commented on source/index.html.md
> +If you are interacting directly with Algorithmia's REST API, provide your API key via an `Authorization` header with the prefix `Simple`. If you are using on of our client libraries, follow the instr
💅 Typo: `on` -> `one`.

2020-04-20 22:22 UTC, andryanmiller commented on source/index.html.md
> +Should an error occur while fulfilling a request, you will be returned an object possessing the following attributes.
💅 Replace `.` with `:`.

2020-04-20 22:25 UTC, andryanmiller commented on source/includes/_algorithms.md
> +    "status": "succeeded",
💅 Add the `resource_type` here.

2020-04-20 22:38 UTC, andryanmiller commented on source/includes/_algorithms.md
> +|`settings.source_visbility`|String|*Required*. Specifies whether the source code for this algorithm will be viewable by any user of the platform. If creating an algorithm with an external repository
:bulb: Update phrasing of "whether the repo is created as public or private" to "whether the created repository is public or private."

2020-04-20 22:40 UTC, andryanmiller commented on source/includes/_scms.md
> +## Returns
💅 Should be `###` not `##`.

2020-04-20 22:48 UTC, andryanmiller commented on source/includes/_algorithms.md
> +|`repository_webhook_secret`|String|The secret used to verify webhook payload generated by an external repository host. [Click here](/developers/algorithm-development/source-code-management#your-repo
💅 Typo: "payload" -> "payloads".

2020-04-20 22:50 UTC, andryanmiller commented on source/index.html.md
> +## Authentication
:bulb: Let's also be sure to mention that users need to enable algorithm management if they wish to use endpoints beyond `/v1algo/`.

2020-04-20 22:54 UTC, andryanmiller commented on source/includes/_algorithm_builds.md
> +|`finished_at`|String|The ISO 8601 datetime at which the build completed.|
💅 Add `resource_type`.

2020-04-20 23:12 UTC, andryanmiller commented on source/includes/_algorithm_builds.md
> +An [algorithm build](#the-algorithm-build-object) object.
💅 Add ", otherwise an error.".

2020-04-20 23:18 UTC, andryanmiller commented on source/includes/_algorithm_versions.md
> +Returns an [algorithm object](#the-algorithm-object) representing the published version, with its `version_info.semantic_version` property having been incremented appropriately from the previous publ
💅 Add ", otherwise an error.".

2020-04-20 23:20 UTC, andryanmiller commented on source/includes/_algorithm_versions.md
> +      "started_at": "2019-05-07T21:16:40.148Z",
💅 Add `resource_type`.

2020-04-20 23:22 UTC, stevielkim requested changes
In the algorithm object and creation section it shows passing in "java" as the language in Python tab UPDATE almost all the code snippets say "Java" as language : https://test.algorithmia.com/developers/api/?python#the-algorithm-object
https://test.algorithmia.com/developers/api/?python#create-an-algorithm

Also would be helpful to have code sample point to specific Python version but i understand it's easier to update code snippets to just Python for language

`algo.create(
  details = {
    "label": "My First Algorithm"
  },
  settings = {
    "language": **"java"**,
    "source_visibility": "closed",
    "license": "apl",
    "network_access": "full",
    "pipeline_enabled": True,
    "environment": "cpu"
  }
)`

When scrolling Nav jumps from "Create an algorithm" code snippet to SCMs "returns" in nav but when you are just scrolling down to "Invoke"
<img width="1440" alt="Screen Shot 2020-04-20 at 4 07 47 PM" src="https://user-images.githubusercontent.com/1320334/79807903-16543c00-8321-11ea-8253-fa952000d6ec.png">

Should show code sample of using query parameters like timeout in: https://test.algorithmia.com/developers/api/?python#invoke-an-algorithm

The nav is out of sync with rest of Slate docs
<img width="1309" alt="Screen Shot 2020-04-20 at 4 12 14 PM" src="https://user-images.githubusercontent.com/1320334/79808125-b4e09d00-8321-11ea-9a70-26054f733cf4.png">

A lot of times users want the file path name .getFile().name but it's missing (old docs didn't have I don't think either) would be nice to list methods available https://test.algorithmia.com/developers/api/?python#get-a-file-or-directory

Nice work! My favorite part is where you mention that a function isn't supported yet which is really helpful to users

2020-04-20 23:35 UTC, andryanmiller commented on source/includes/_data.md
> +|`connector_id`|String|The ID of the specific connector you wish to create directory within. Learn more in the [connectors section](#connectors) above.|
💅 Typo: "create directory within" -> "create a directory within".

2020-04-20 23:42 UTC, andryanmiller commented
Let's ensure that, wherever we mention admin API keys, that we link to the appropriate section in the API keys docs.

2020-04-20 23:48 UTC, andryanmiller commented on source/includes/_data.md
> +Paths are contextual to the data connector you are interacting with. For example, paths for the `data` connector must begin first with the username of user who owns the collection you wish to interac
Typo: "username of user" -> "username of the user".

2020-04-20 23:49 UTC, andryanmiller commented on source/includes/_data.md
> +Paths are contextual to the data connector you are interacting with. For example, paths for the `data` connector must begin first with the username of user who owns the collection you wish to interac
Also, "you must supply the name of the bucket as the first component of the data" -> "you must supply the name of the bucket as the first component of the data URI".

2020-04-21 16:26 UTC, andryanmiller commented on source/includes/_users.md
> +`POST /v1/users`
💅 Remove `/v1/`.

2020-04-21 16:26 UTC, andryanmiller commented on source/includes/_users.md
> +|`username`|String|*Required*. The unique identifier for this user. Only letters, numbers, and underscores are permitted.|
💅 Note that this field must begin with a letter.

2020-04-21 16:36 UTC, andryanmiller commented on source/includes/_users.md
> +|`limit`|Number|The maximum number of items to return in the response. Defaults to 10.|
💅 This limit is actually `50` by default.

2020-04-21 16:42 UTC, andryanmiller commented on source/includes/_users.md
> +`GET /users`
💅 Please add the `GET /users/:username` route as well.

2020-04-22 01:07 UTC, stevielkim approved these changes

2020-04-22 17:16 UTC, merged